dist: xenial
language: python
sudo: required
python:
    - "3.7"

before_install:
    - openssl aes-256-cbc -K $encrypted_e718e6de09bb_key -iv $encrypted_e718e6de09bb_iv -in .env.tar.enc -out .env.tar -d
    - tar xf .env.tar

install:
    - make install
    - install-terraform

script:
- make script

env:
    global:
        # AWS_ACCESS_KEY_ID
        - secure: "DusutX0EUIVvcgbsBZLQ3EoSuq9A7ddMCfYC1KHXCNCvkt/1PSsI+bE03dMfOh2JFRFjNP1w+opRyNdTaJZBvgQWisGdrMrRlZSK2vvE2QlySVC0/KTR3CxoCDxb+D/Ak2IKE9/aT/Gdspqg+0HjJ+R/hHt9MfdAL12uGnecqXebpbkRrd0rblLnqZFpInWSJKmdwEMsZIGNZq+yJi7LOucVue3AdIRcUJVk/Jbnisf9zmuU2rOsU1ydRg+6iwgG8DjCBsyEpEDrnuI06GV5mxxdFvmcz0xdGWtBPHyt7F9FIyPOpaRdo8gaG3wC69gFaPWHWpjVi6ROAxzbY082U4CxHsnZ8RdF73eZRBjrKC41AhjvVsqtStImMtAU0F64xQgq3lnOyejiCJDiLoVlwnHAeilUbcsYeqBia7SupjwgnsJwjHOxg+ba71DnVNjPb0qLrg45WEkzSLr40IexHISOoU6KNC65xY2UxyxJjolaIrQGXzXb6qn/Jjw6S31S+ATH1bIWmEFm9z30HgkZLAQW4CqyFS6nbXoXZDnkAufHa0z/uzcqWIXPFbziZ7c13SZB2eJman1bdk8AZ9kZ9KyDFnli+RatoGfGdlsN05uCczzqZPIsC7Q8Y0mKGczp4ty3ZhVGNKRdSgK0I8b5L9+8rGt70ZZguaD3/BBUUBg="
        # AWS_SECRET_ACCESS_KEY
        - secure: "mHoa/Qff6JO5YTrMMeQ+MRgxT4IR0fRh0P2F88+gH/elDTEpViYTf1Q/WL1ZmtGRlRWDU3A8EWVJ5LqYqktywR3qXuihzxzte12TE2sbrhET+cEP1UTeSp3CdGjGYoHx3MbwwY2IWDYK1TuudeGXnS8sw4CCkDtvJPRu/snjR8fLyB5EPBO6u1COGY6MauWWIl5x4QX2avmCc4Rcf1Ae6wiS8IlGXvAe5NJK6qqcwkWqPwd/MfxE5QrN0rLcQET1pDGs/D2zi/2PihbmIZ6QqmjKBb2fuFdVwNIJP93toUSIuHaqplS14Usn8S8BS/AkkVQUhxl83E0eb/LBs1gqMGOF2J5oeILEim1J39pRicNwfvV9pqz2VNhdRxkHLChUywx+Rk7+hagliG0vMeTNhpOhZuVT19c25EmlEue6I5G9qej8xzsYPMr6YLVRnyZwq4eCL5yIatLGM7dMueNcWoxLem+crykZtWWwywyrcLCiPJ903Q8n36utbh3kDtB3EN7HNasznf0l44qZMaRgiw3ro5rnzoLKSC4CWh9nAhGphnhNkDC3r4pqkQC+H3Br9PLjX4kTQbWmwqT5GqFWk/uuC98Q/gblFPqmMMO07YEaEYkhp74JJlcVGEpIUqJnFxY5a8RvmpaTiFoQWFR3gqLVGgJWFOuUj2T5j86wDag="
        # AWS_DEFAULT_REGION
        - secure: "cMSwgqy16Q+YxH36ScPOgxDeQdi+tbUsGJMWqqCJmUKEta9S4s4kRBZObT1IliZ9mM380phdE0AirM4pwXzbrwFifC8YcDfdI9ISXtJRDHk2nLBSb6WVHGCJ/r1nXzlhrRfrmBkGvDeAb9W1mCAG/Xd6SwqFbKnc0wkam5TPpKIen1XYKOBlMy7X61cMbN1Ga/TwFv1T+TNELu3+7iEFDGm9RBW+xa0oytcUDEeFW9VGaWcBPWdgpZ3kIFoTPHBZXaa4FscKwO0EhUanWFQno7r4JsnbFhnkc0YHijfOce+hs7ZMqgLU68y6pc07ubeQBOvL/305SpUowNrFE2mJQehYxK8HMAWho2HjoaV+8o/GB1TEnEI4R+A0FFUq6pVkez8/fgPj2GHgBQ4wSnAakjqfPoRozh4L+ueJakQNmi7l78KxMUeEZ2x0I/wS00OpV5jVsH2WahuUQ+pZ/GuwUqGzH0dozVAd+eEd7JDps0nw9MTjDrDFq4HWKFEolrOKlpxrukLWTUF2NSfz/C2+OzAsAoCMECzjVMu2RRcSeKfbD2I3N3kdFYzH9NzC3eItO6NmQOCZcNYjh0Oh0msSRlj7gR8kbUbMaS18DGyTRnwlzXCHZqEEGrwwDCpJnm8log75Kllk1+gUoKXFszE9g03LN6HhoRRKlzc4MUvyFs0="
        # GITHUB_TOKEN
        - secure: "hwYkggw/xaL8leDBaHCxfH8hwHgatmvm6xn5liWxWpQWazcVCMRYd3g1Y2suUw3gGNn5g4FFopRVs28G7g4Y/wRio6hKbVv9mROoenM/rx/ULZSyhurvlCfxH/Oey4UnFC+KePLl4ZaLDGZe9mqDV+tjFACq1t2zRk1o8G6FoDc6LL5SyxxdhaHs+Ow0A/kNWq8eOWFYCD7vDmhDOIT+YrSAFYCZqzdJwKK6KqKnYOKscB/k+Tqs+lB5W4czJKzsUIoO9YdkZjY57C13Z/3GEp6FRaD5R+cN2FsP2OI8NMADz8QfmJaFuHDhfnJf0dzsC8rY8pn/QbOsCAXSmz9N6ZwpWjgxj9NoURBDNku2mh2heBxaxjeZKLqOx8Cymbvc2pRLk3EuRR0+i0p8kD8/CRVZm4QZ3E5bcbAv21QHivPGqQc1vamspAGBVUdaxDWxM1i4P6E2i/B4cT2DQZ/t14GiQyEi3LQpFILBmkz+QnDG4yGqy9a6JWNVvtzF77pbADyPJKFtZsdUIBKHxL/Yx9P5nvMAfK1quzcjuUHYDsRThS2uf281OCcyMZGuxadkaURofR1v0Pa1IwwwQ2ttYYdGLESqCD7k13jwGX4cYNtT1FbRQwm36HZqNnfT2jcWRa70nv8sTaRi+DkbHeJo0DwyRtNzQBDTR1HJMOUW1dQ="
