dist: xenial
language: python
sudo: required
python:
    - "3.7"

before_install:
    - openssl aes-256-cbc -K $encrypted_e718e6de09bb_key -iv $encrypted_e718e6de09bb_iv -in .env.tar.enc -out .env.tar -d
    - tar xf .env.tar

install:
    - make install
    - install-terraform

script:
- make script
